// The byte-level BPE tokenizer, re-implemented against the vocabulary the
// models were trained with (`blocks.py: BPETokenizer`, a HuggingFace
// `tokenizers` BPE dumped to JSON by `sodachat.export_onnx`).
//
// A model is only as good as the ids it is fed, and an id here is not a
// judgement call: every string must encode to exactly what Python produced, or
// the prompt the model sees is not the prompt it was trained on. `tools/
// check_tokenizer.mjs` holds this to that standard against ids generated by
// the Python tokenizer.
//
// The three stages mirror the trained pipeline, in order:
//   1. added tokens  — "<|chat|>" and friends survive as single units, matched
//                      literally before anything else touches the text
//   2. ByteLevel     — split on the GPT-2 regex, then map each UTF-8 *byte* to
//                      a printable stand-in character (so no byte is unencodable
//                      and there is no unknown token at all)
//   3. BPE           — repeatedly merge the adjacent pair with the best rank

// GPT-2's pre-tokenizer pattern, as `pre_tokenizers.ByteLevel(use_regex=True)`
// applies it. Contractions, then letters, then numbers, then punctuation runs,
// then whitespace — with a leading space glued to the token that follows it,
// which is why `build_prompt` deliberately ends on "B:" and no trailing space.
const PRE_TOKENIZE =
  /'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+/gu;

// The byte <-> character alphabet ByteLevel uses: the 188 bytes that are
// already printable map to themselves, and the remaining 68 are shifted up into
// an unused block so that every byte has a visible, single-char representation.
function byteAlphabet() {
  const printable = [];
  for (let b = 33; b <= 126; b++) printable.push(b);
  for (let b = 161; b <= 172; b++) printable.push(b);
  for (let b = 174; b <= 255; b++) printable.push(b);
  const byteToChar = new Array(256);
  let extra = 0;
  for (let b = 0; b < 256; b++) {
    if (printable.includes(b)) {
      byteToChar[b] = String.fromCharCode(b);
    } else {
      byteToChar[b] = String.fromCharCode(256 + extra);
      extra += 1;
    }
  }
  const charToByte = new Map(byteToChar.map((c, b) => [c, b]));
  return { byteToChar, charToByte };
}

const { byteToChar, charToByte } = byteAlphabet();

export class Tokenizer {
  constructor(spec) {
    this.vocab = spec.model.vocab;
    this.idToToken = [];
    for (const [token, id] of Object.entries(this.vocab)) this.idToToken[id] = token;

    // Merge rank = position in the merges list; lower wins.
    this.ranks = new Map();
    spec.model.merges.forEach((merge, i) => {
      const [a, b] = Array.isArray(merge) ? merge : merge.split(" ");
      this.ranks.set(a + " " + b, i);
    });

    // Added tokens live outside the BPE vocabulary and are matched verbatim.
    // Longest-first, so "<|answer|>" is never shadowed by a shorter prefix.
    this.added = new Map();
    for (const t of spec.added_tokens || []) {
      this.added.set(t.content, t.id);
      this.idToToken[t.id] = t.content;
    }
    this.addedContents = [...this.added.keys()].sort((a, b) => b.length - a.length);
    this.specialIds = new Set(this.added.values());
    this.size = Math.max(
      Object.keys(this.vocab).length,
      ...[...this.added.values()].map((i) => i + 1),
    );
    this.cache = new Map();
    this.encoder = new TextEncoder();
    this.decoder = new TextDecoder("utf-8");
  }

  static fromJSON(spec) {
    return new Tokenizer(typeof spec === "string" ? JSON.parse(spec) : spec);
  }

  /** BPE over one pre-token, already mapped into the byte alphabet. */
  _bpe(word) {
    const hit = this.cache.get(word);
    if (hit) return hit;
    let symbols = [...word];
    while (symbols.length > 1) {
      let bestRank = Infinity;
      let bestAt = -1;
      for (let i = 0; i < symbols.length - 1; i++) {
        const rank = this.ranks.get(symbols[i] + " " + symbols[i + 1]);
        if (rank !== undefined && rank < bestRank) {
          bestRank = rank;
          bestAt = i;
        }
      }
      if (bestAt < 0) break;
      symbols = [
        ...symbols.slice(0, bestAt),
        symbols[bestAt] + symbols[bestAt + 1],
        ...symbols.slice(bestAt + 2),
      ];
    }
    this.cache.set(word, symbols);
    return symbols;
  }

  /** Text -> token ids, matching `BPETokenizer.encode`. */
  encode(text) {
    const ids = [];
    for (const [chunk, addedId] of this._splitAdded(text)) {
      if (addedId !== null) {
        ids.push(addedId);
        continue;
      }
      for (const [piece] of chunk.matchAll(PRE_TOKENIZE)) {
        let mapped = "";
        for (const byte of this.encoder.encode(piece)) mapped += byteToChar[byte];
        for (const symbol of this._bpe(mapped)) {
          const id = this.vocab[symbol];
          // The alphabet is closed over every byte, so a symbol with no id can
          // only mean a corrupt vocabulary — better to say so than to drop it
          // and hand the model a subtly different prompt.
          if (id === undefined) throw new Error(`token ${symbol} is not in the vocabulary`);
          ids.push(id);
        }
      }
    }
    return ids;
  }

  /** Cut `text` on added tokens, yielding [chunk, null] | ["", id] in order. */
  _splitAdded(text) {
    if (!this.addedContents.length) return [[text, null]];
    const out = [];
    let rest = text;
    while (rest.length) {
      let at = -1;
      let found = null;
      for (const content of this.addedContents) {
        const i = rest.indexOf(content);
        // Earliest match wins; ties go to the longer token (sorted first).
        if (i >= 0 && (at < 0 || i < at)) {
          at = i;
          found = content;
        }
      }
      if (at < 0) break;
      if (at > 0) out.push([rest.slice(0, at), null]);
      out.push(["", this.added.get(found)]);
      rest = rest.slice(at + found.length);
    }
    if (rest.length) out.push([rest, null]);
    return out;
  }

  /** Token ids -> text, matching `BPETokenizer.decode` (which drops specials). */
  decode(ids, { skipSpecial = true } = {}) {
    let mapped = "";
    for (const id of ids) {
      if (skipSpecial && this.specialIds.has(id)) continue;
      const token = this.idToToken[id];
      if (token === undefined) continue;
      mapped += token;
    }
    const bytes = new Uint8Array(mapped.length);
    let n = 0;
    for (const ch of mapped) {
      const byte = charToByte.get(ch);
      // A character outside the alphabet cannot come from a real token; skip it
      // rather than writing a garbage byte into the middle of a UTF-8 sequence.
      if (byte !== undefined) bytes[n++] = byte;
    }
    return this.decoder.decode(bytes.subarray(0, n));
  }

  /** The id of an added token, e.g. "<|end|>". */
  tokenId(token) {
    const id = this.added.get(token) ?? this.vocab[token];
    if (id === undefined) throw new Error(`token ${token} is not in the vocabulary`);
    return id;
  }
}
